CREATE TABLE Usuarios (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Nome VARCHAR(100) NOT NULL,
  UsuarioLogin VARCHAR(50) NOT NULL UNIQUE,
  SenhaSalt VARBINARY(16) NOT NULL,
  SenhaHash VARBINARY(32) NOT NULL
);

CREATE TABLE Enderecos (
  Id INT PRIMARY KEY IDENTITY(1,1),
  Cep VARCHAR(9) NOT NULL,
  Logradouro VARCHAR(150) NOT NULL,
  Complemento VARCHAR(100) NULL,
  Bairro VARCHAR(100) NOT NULL,
  Cidade VARCHAR(100) NOT NULL,
  Uf CHAR(2) NOT NULL,
  Numero VARCHAR(10) NOT NULL,
  UsuarioId INT NOT NULL,
  CONSTRAINT FK_Enderecos_Usuarios FOREIGN KEY (UsuarioId) REFERENCES Usuarios(Id)
);